Migrating bot commands
Black0nion/BlackOnion-Bot pull request #181
Opened 2022-04-21 02:28 UTC by RealYusufIsmail

# PR Title
### Checklist

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines](/CONTRIBUTING.md).
- [x] I agree with the [license](/LICENSE).

### Changes
- [ ] Refactoring
- [x] Internal code
- [ ] External Code / Libraries
- [ ] Documentation
- [ ] Other: \_____

Closes Issue: -

## Description
I have migrated the bot commands to slash commands.

2022-04-21 15:03 UTC, RealYusufIsmail commented
Help command left

2022-04-22 09:26 UTC, SIMULATAN requested changes
Some nitpicking, sorry for that 😬

Also, I haven't tested it yet, I'll do that in like 30 mins or something

2022-04-22 09:26 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/commands/bot/AntiSpoilerCommand.java
> +			e.replyEmbeds(EmbedUtils.getSuccessEmbed(author, guild).addField("antispoilerstatuschanged", cmde.getTranslation("antispoileris", new Placeholder("status", cmde.getTranslation("off"))), false).bui
Yet another occurance of shitty legacy code, please do it like [this](https://github.com/Black0nion/BlackOnion-Bot/blob/main/src/main/java/com/github/black0nion/blackonionbot/commands/bot/AntiSwearCommand.java#L32-L43).

Also, thanks for replacing the Utils.checkPermission

2022-04-22 09:26 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/commands/bot/AntiSpoilerCommand.java
> -			message.replyEmbeds(EmbedUtils.getSuccessEmbed(author, guild).addField(LanguageSystem.getTranslation("antispoilerstatus", author, guild).replace("%status%", LanguageSystem.getTranslation(guild.get
I'd still keep this, but with the new way of responding.
This way, you can still check the status of the system

2022-04-22 09:26 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/commands/bot/AntiSpoilerCommand.java
> +						.addChoice("off", "off")))
Please make this optional to allow checking the status of the system (see below)

2022-04-22 09:26 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/commands/bot/AntiSwearCommand.java
>  		} else {
Why did you replace the "generic" variant with hardcoded ifs?

2022-04-22 09:26 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/commands/bot/AntiSwearCommand.java
> -			message.replyEmbeds(EmbedUtils.getSuccessEmbed(author, guild).addField(LanguageSystem.getTranslation("antiswearstatus", author, guild).replace("%status%", LanguageSystem.getTranslation(guild.getAn
Same as AntiSpoilerCommand, please still allow checking the status

2022-04-22 09:26 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/commands/bot/HelpCommand.java
> +		if(command != null) {
Missing space

2022-04-22 09:26 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/commands/bot/SupportCommand.java
> +		super(builder(Commands.slash("support", "Used to get support.")));
If you want, you can use `super("support", "Used to get support.")` directly, but this is also completely fine

2022-04-22 18:10 UTC, RealYusufIsmail commented
Seems like everything works

2022-04-24 16:20 UTC, SIMULATAN commented
TODO for me: recode /help command with paginator

2022-04-24 16:33 UTC, SIMULATAN approved these changes

2022-04-24 16:35 UTC, merged