Migrating fun commands
Black0nion/BlackOnion-Bot pull request #183
Opened 2022-04-22 06:33 UTC by RealYusufIsmail

# PR Title
### Checklist

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines](/CONTRIBUTING.md).
- [x] I agree with the [license](/LICENSE).

### Changes
- [ ] Refactoring
- [x] Internal code
- [ ] External Code / Libraries
- [ ] Documentation
- [ ] Other: \_____

Closes Issue: -

## Description
I am migrating the fun commands to slash command.

2022-04-23 15:51 UTC, RealYusufIsmail commented
@SIMULATAN can you please review this pr after #181

2022-04-23 17:26 UTC, SIMULATAN commented
sure

2022-04-24 09:28 UTC, SIMULATAN requested changes

2022-04-24 09:28 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/commands/bot/HelpCommand.java
> +                            if (c.isHidden(author)) {
shouldn't this be inverted?

2022-04-24 09:28 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/commands/bot/HelpCommand.java
> +                            if (c.isHidden(user)) {
same as above

2022-04-24 09:28 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/commands/bot/HelpCommand.java
> +                    if (entry.getValue().getValue().isHidden(user) && (entry.getValue().getValue().getCategory() == category))
Please extract the `entry.getValue().getValue()` as it gets called a good few times here

2022-04-24 09:28 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/systems/antispoiler/AntiSpoilerSystem.java
> +		final Message msg = interactionEvent.getTextChannel().retrieveMessageById(interactionEvent.getTextChannel().getLatestMessageIdLong()).complete();
This probably won't work because we also want to remove spoilers on non-interaction events

2022-04-24 10:40 UTC, RealYusufIsmail commented on src/main/java/com/github/black0nion/blackonionbot/commands/bot/HelpCommand.java
> +                            if (c.isHidden(author)) {
oh i see

2022-04-24 11:02 UTC, RealYusufIsmail commented
This pr is blocked until #181 is merged

2022-04-24 11:43 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/systems/ReactionRoleSystem.java
> +				logger.error("Emoji nicht erkannt: '{}'", e.getReactionEmote().getName());
Please translate this to "Unknown Emoji: '{}'"

2022-04-24 11:43 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/systems/ReactionRoleSystem.java
> +				logger.error("Emoji nicht erkannt: '{}'", e.getReactionEmote().getName());
see below

2022-04-24 14:02 UTC, SIMULATAN requested changes

2022-04-24 14:02 UTC, SIMULATAN commented on src/main/resources/translations/English.json
> +  "istimedout": "The member is already time out.",
```suggestion
  "istimedout": "The member is already timed out.",
```

2022-04-24 16:57 UTC, SIMULATAN requested changes

2022-04-24 16:57 UTC, SIMULATAN commented on src/main/java/com/github/black0nion/blackonionbot/slashcommands/information/UserInfoCommand.java
> +                .addOption(OptionType.USER,USER, "The member to get information about.", false)));
missing space

2022-05-02 09:57 UTC, closed without merging